version: '3.8'

services:
  frontend:
    build: .
    container_name: fleet-frontend
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    networks:
      - fleetlink-network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    image: fleetlink-backend:latest  # Assumes backend image is built
    container_name: fleet-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - fleetlink-network
    restart: unless-stopped

networks:
  fleetlink-network:
    driver: bridge
